server:
  port: 9300

spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://193.168.1.200:3306/ygsquality?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      idle-timeout: 30000
      connection-timeout: 30000
      auto-commit: true
  redis:
    database: 0
    host: 193.168.1.200
    port: 6379
    password:

swagger:
  enable: true
